spring:
  datasource:
    url: jdbc:mysql://192.168.60.128:3306/chainmaker_ca?useSSL=false&serverTimezone=UTC
    username: chainmaker_ca
    password: nacl983258108
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl