spring:
  datasource:
    url: jdbc:mysql://192.168.60.128:3306/chainmaker_ca?useSSL=false&serverTimezone=UTC
    username: chainmaker_ca
    password: nacl983258108
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

ca:
  url: http://192.168.60.128:8090/api/ca
  username: admin1
  password: passw0rd
  org: TestCMorg1
  country: CN
  locality: GZ
  province: GD
